# Generated by Django 4.1.1 on 2023-10-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='urunler/', verbose_name='Ürün Resmi'),
        ),
    ]
